### ISSUE TITLE
Python3 version

### ISSUE THREAD

**Issue by markatdxb** [cbabs/solarwinds-ansible-inv#2]
Hello, 
first of all many thanks for making this great script. it works like a charm in our environment !!!. 
I have one question  - do plan have any plans to make a Python3 compatible version ? I tried to run but getting various errors and as im not that proficient in Py im unable to fix it :( 
thanks
Mark

**Comment by Rionoska3** [comment]
> Hello,
> first of all many thanks for making this great script. it works like a charm in our environment !!!.
> I have one question - do plan have any plans to make a Python3 compatible version ? I tried to run but getting various errors and as im not that proficient in Py im unable to fix it :(
> thanks
> Mark

While I'm also not profecient in Python, found if you just hardcoded the config file values and commented out the initial references to "configparser" it would run under python3. That being said, I don't recommend doing this.

It would be great if the readme was expanded upon for folks just getting started with python and perhaps some examples of other working queries. I edited the "payload" query and am able to pull back a list of servers via https://solarwinds/Orion/Admin/swis.aspx, however when I run this script it appears to return nothing:
  warnings.warn(
{
  "_meta": {
    "hostvars": {}
  }
}

**Comment by dkhenderson2** [comment]
Make sure when you run the script you use the --list  cli arg

example :
python3 swinds.py --list

That should return the list of  servers.

**Comment by dkhenderson2** [comment]
to allow it to run in python3 change the Module ConfigParser, to configparser. In Python 3, ConfigParser has been renamed to configparser for PEP 8 compliance.

change the line 31 to:
import configparser
and 
change the line 44 to:
config = configparser.ConfigParser()
